DROP TABLE CITY IF EXISTS;
CREATE TABLE CITY (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100) NOT NULL,
    STATE VARCHAR (100) NOT NULL,
    COUNTRY VARCHAR (100) NOT NULL,
    MAP VARCHAR (100) NOT NULL
);